### ISSUE TITLE
Object error upon loading map into darkplaces.

### ISSUE THREAD

**Issue by eGax** [plankatron/quakemash#7]
Under my linux desktop the map loads after a few seconds with a few issues that can be seen in the console history. This is for the object error. 

======OBJECT ERROR======

server EDICT 5181:
absmin         '-1 -1 -1'
absmax         '1 1 1'
solid          1
classname      trigger_teleport
model          
touch          teleport_touch()
server OBJECT ERROR in trigger_teleport:
no target
Tip: read above for entity information
Connection accepted to local:1
<-- server to client keepalive

Server: DarkPlaces-Quake build 18:34:06 May 16 2016 - release (progs 51103 crc)

**Comment by plankatron** [comment]
fixed this
